spring:
  application:
    name: streamer
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            user-name-attribute: email
            scope:
              - profile
              - email
          google-youtube:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            user-name-attribute: email
            scope:
              - profile
              - email
              - https://www.googleapis.com/auth/youtube.upload
              - https://www.googleapis.com/auth/youtube.readonly
              - https://www.googleapis.com/auth/youtube.force-ssl
  datasource:
    url: jdbc:h2:file:./data/afklive;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: PT720H
  sql:
    init:
      mode: always
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:user}
    password: ${SMTP_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      
rate-limiter:
  capacity: 10
  refill-tokens: 1

app:
  gemini:
    key: ${GEMINI_API_KEY:}
  storage:
    type: ${STORAGE_TYPE:local}
    endpoint: ${DO_SPACES_ENDPOINT}
    region: ${DO_SPACES_REGION}
    bucket: ${DO_SPACES_BUCKET}
    access-key: ${DO_SPACES_KEY}
    secret-key: ${DO_SPACES_SECRET}

server:
  forward-headers-strategy: native
