server:
  port: 8081

spring:
  application:
    name: streamer-jobs
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:afkdb}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          google-youtube:
            client-id: ${GOOGLE_YOUTUBE_CLIENT_ID}
            client-secret: ${GOOGLE_YOUTUBE_CLIENT_SECRET}
            provider: google
            scope:
              - https://www.googleapis.com/auth/youtube.upload
              - https://www.googleapis.com/auth/youtube.readonly
              - https://www.googleapis.com/auth/youtube.force-ssl
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:user}
    password: ${SMTP_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_STARTTLS_ENABLE:true}

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
    database:
      type: postgres

app:
  email:
    support: ${APP_EMAIL_SUPPORT:test@test.com}
    no-reply: ${APP_EMAIL_NO_REPLY:test@test.com}
  zeptomail:
    url: ${ZEPTOMAIL_URL:}
    token: ${ZEPTOMAIL_TOKEN:}
  gemini:
    key: ${GEMINI_API_KEY:}
  storage:
    type: ${STORAGE_TYPE:local}
    endpoint: ${DO_SPACES_ENDPOINT}
    region: ${DO_SPACES_REGION}
    bucket: ${DO_SPACES_BUCKET}
    access-key: ${DO_SPACES_KEY}
    secret-key: ${DO_SPACES_SECRET}
  aws:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: eu-north-1
    function-name: afklive-optimizer-lambda
