spring:
  application:
    name: streamer
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
      resolve-lazily: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            user-name-attribute: email
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          google-youtube:
            client-id: ${GOOGLE_YOUTUBE_CLIENT_ID}
            client-secret: ${GOOGLE_YOUTUBE_CLIENT_SECRET}
            user-name-attribute: email
            provider: google
            scope:
              - profile
              - email
              - https://www.googleapis.com/auth/youtube.upload
              - https://www.googleapis.com/auth/youtube.readonly
              - https://www.googleapis.com/auth/youtube.force-ssl
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:afklive}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: PT720H
  sql:
    init:
      mode: always
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:user}
    password: ${SMTP_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_STARTTLS_ENABLE:true}
      
rate-limiter:
  capacity: 10
  refill-tokens: 1

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  gemini:
    key: ${GEMINI_API_KEY:}
  storage:
    type: ${STORAGE_TYPE:local}
    endpoint: ${DO_SPACES_ENDPOINT}
    region: ${DO_SPACES_REGION}
    bucket: ${DO_SPACES_BUCKET}
    access-key: ${DO_SPACES_KEY}
    secret-key: ${DO_SPACES_SECRET}
  aws:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: eu-north-1
    function-name: afklive-optimizer-lambda
  phonepe:
    merchant-id: ${PHONEPE_MERCHANT_ID:PGTESTPAYUAT}
    salt-key: ${PHONEPE_SALT_KEY:099eb0cd-02cf-4e2a-8aca-3e6c6aff0399}
    salt-index: ${PHONEPE_SALT_INDEX:1}
    salt-env: ${PHONEPE_ENV:https://api-preprod.phonepe.com/apis/pg-sandbox}
server:
  forward-headers-strategy: native
